# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Mjc5NWFkZjU1NDc5YTYwZWNmYjRmOGMxN2NhZDhhYmM5NmEwYjg1YTZjZmMyOGY4YmJhOTU5ODFjYjllYTI1YmNhZjBhY2NlYzg0YzE2ZDJlMDRiNzk5ODAwMjlhN2E3MDEzOGExMjAxNzFiNTYyMjc1OGNlYzZiYTUzZjBjN2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
